/**
 * @file   StimuliITS.cpp
 * @author Simon Voigt Nesbo
 * @date   November 19, 2018
 * @brief  Source file for Stimuli class for ITS
 */

#include "StimuliITS.hpp"
#include "Detector/Common/DetectorSimulationStats.hpp"

// Ignore warnings about use of auto_ptr and unused parameters in SystemC library
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#include <systemc.h>
#pragma GCC diagnostic pop

#include <list>
#include <sstream>
#include <fstream>

extern volatile bool g_terminate_program;


SC_HAS_PROCESS(StimuliITS);
///@brief Constructor for stimuli class.
///       Instantiates and initializes the event generator and Alpide objects,
///       connects the SystemC ports
///@param[in] name SystemC module name
///@param[in] settings QSettings object with simulation settings.
///@param[in] output_path Path to store output files generated by the Stimuli class
StimuliITS::StimuliITS(sc_core::sc_module_name name, QSettings* settings, std::string output_path)
  : StimuliBase(name, settings, output_path)
{
  std::cout << "Layer 0 hit density: ";
  std::cout << settings->value("event/hit_density_layer0").toDouble() << std::endl;

  std::cout << "Layer 1 hit density: ";
  std::cout << settings->value("event/hit_density_layer1").toDouble() << std::endl;

  std::cout << "Layer 2 hit density: ";
  std::cout << settings->value("event/hit_density_layer2").toDouble() << std::endl;

  std::cout << "Layer 3 hit density: ";
  std::cout << settings->value("event/hit_density_layer3").toDouble() << std::endl;

  std::cout << "Layer 4 hit density: ";
  std::cout << settings->value("event/hit_density_layer4").toDouble() << std::endl;

  std::cout << "Layer 5 hit density: ";
  std::cout << settings->value("event/hit_density_layer5").toDouble() << std::endl;

  std::cout << "Layer 6 hit density: ";
  std::cout << settings->value("event/hit_density_layer6").toDouble() << std::endl;

  std::cout << "Layer 0 number of staves: ";
  std::cout << settings->value("its/layer0_num_staves").toUInt() << std::endl;

  std::cout << "Layer 1 number of staves: ";
  std::cout << settings->value("its/layer1_num_staves").toUInt() << std::endl;

  std::cout << "Layer 2 number of staves: ";
  std::cout << settings->value("its/layer2_num_staves").toUInt() << std::endl;

  std::cout << "Layer 3 number of staves: ";
  std::cout << settings->value("its/layer3_num_staves").toUInt() << std::endl;

  std::cout << "Layer 4 number of staves: ";
  std::cout << settings->value("its/layer4_num_staves").toUInt() << std::endl;

  std::cout << "Layer 5 number of staves: ";
  std::cout << settings->value("its/layer5_num_staves").toUInt() << std::endl;

  std::cout << "Layer 6 number of staves: ";
  std::cout << settings->value("its/layer6_num_staves").toUInt() << std::endl;

  ITS::ITSDetectorConfig config;
  config.layer[0].num_staves = settings->value("its/layer0_num_staves").toUInt();
  config.layer[1].num_staves = settings->value("its/layer1_num_staves").toUInt();
  config.layer[2].num_staves = settings->value("its/layer2_num_staves").toUInt();
  config.layer[3].num_staves = settings->value("its/layer3_num_staves").toUInt();
  config.layer[4].num_staves = settings->value("its/layer4_num_staves").toUInt();
  config.layer[5].num_staves = settings->value("its/layer5_num_staves").toUInt();
  config.layer[6].num_staves = settings->value("its/layer6_num_staves").toUInt();
  config.chip_cfg = mChipCfg;

  mEventGen = std::move(std::unique_ptr<EventGenITS>(new EventGenITS("event_gen",
                                                                     config,
                                                                     settings,
                                                                     mOutputPath)));

  if(mSingleChipSimulation) {
    mAlpide = std::move(std::unique_ptr<ITS::SingleChip>(new ITS::SingleChip("SingleChip",
                                                                             0,
                                                                             mChipCfg)));

    mAlpide->s_system_clk_in(clock);

    mReadoutUnit = std::move(std::unique_ptr<ReadoutUnit>(new ReadoutUnit("RU",
                                                                          0,
                                                                          0,
                                                                          1,
                                                                          1,
                                                                          mTriggerFilterTimeNs,
                                                                          mTriggerFilterEnabled,
                                                                          true,
                                                                          mDataRateIntervalNs)));

    mReadoutUnit->s_busy_in(mReadoutUnit->s_busy_out);
    mReadoutUnit->s_system_clk_in(clock);
    mReadoutUnit->s_serial_data_input[0](mAlpide->s_alpide_data_out_exp);
    mReadoutUnit->s_serial_data_trig_id[0](mAlpide->s_serial_data_trig_id_exp);
    mReadoutUnit->s_alpide_control_output[0].bind(mAlpide->socket_control_in[0]);
    mAlpide->socket_data_out[0].bind(mReadoutUnit->s_alpide_data_input[0]);
  }
  else { // ITS Detector Simulation
    mITS = std::move(std::unique_ptr<ITS::ITSDetector>(new ITS::ITSDetector("ITS", config,
                                                                            mTriggerFilterTimeNs,
                                                                            mTriggerFilterEnabled,
                                                                            mDataRateIntervalNs)));
    mITS->s_system_clk_in(clock);
    mITS->s_detector_busy_out(s_its_busy);
  }

  s_physics_event = false;

  if(mSystemContinuousMode == true) {
    SC_METHOD(continuousTriggerMethod);
  }

  SC_METHOD(stimuliMainMethod);
  sensitive << mEventGen->E_triggered_event;
  dont_initialize();

  SC_METHOD(stimuliQedNoiseEventMethod);
  sensitive << mEventGen->E_untriggered_event;
  dont_initialize();

  // This method just generates a (VCD traceable) SystemC signal
  // that coincides with the physics event from the event generator
  SC_METHOD(physicsEventSignalMethod);
  sensitive << mEventGen->E_triggered_event;
  dont_initialize();
}


///@brief Main control of simulation stimuli
void StimuliITS::stimuliMainMethod(void)
{
  if(simulation_done == true || g_terminate_program == true) {
    int64_t time_now = sc_time_stamp().value();
    std::cout << "@ " << time_now << " ns: \tSimulation done" << std::endl;

    sc_core::sc_stop();

    writeStimuliInfo();

    if(mSingleChipSimulation)
      Detector::writeAlpideStatsToFile(mOutputPath,
                                       mAlpide->getChips(),
                                       &ITS::ITS_global_chip_id_to_position);
    else
      mITS->writeSimulationStats(mOutputPath);

    mEventGen->writeSimulationStats(mOutputPath);
  }
  // We want to stop at n_events, not n_events-1.
  else if(mEventGen->getTriggeredEventCount() <= mNumEvents) {
    //if((mEventGen->getPhysicsEventCount() % 100) == 0) {
    int64_t time_now = sc_time_stamp().value();
    std::cout << "@ " << time_now << " ns: \tPhysics event number ";
    std::cout << mEventGen->getTriggeredEventCount() << std::endl;
    //}

    std::cout << "Feeding " << mEventGen->getTriggeredEvent().size() << " pixels to ITS detector." << std::endl;
    // Get hits for this event, and "feed" them to the ITS detector
    auto event_hits = mEventGen->getTriggeredEvent();

    if(mSingleChipSimulation) {
      for(auto it = event_hits.begin(); it != event_hits.end(); it++)
        mAlpide->pixelInput(*it);

      std::cout << "Creating event for next trigger.." << std::endl;

      if(mSystemContinuousMode == false) {
        // Create an event for the next trigger, delayed by the
        // total/specified trigger delay (to account for cable/CTP delays etc.)
        mReadoutUnit->E_trigger_in.notify(mTriggerDelayNs, SC_NS);
      }
    }
    else {
      for(auto it = event_hits.begin(); it != event_hits.end(); it++)
        mITS->pixelInput(*it);

      std::cout << "Creating event for next trigger.." << std::endl;

      if(mSystemContinuousMode == false) {
      // Create an event for the next trigger, delayed by the
      // total/specified trigger delay (to account for cable/CTP delays etc.)
        mITS->E_trigger_in.notify(mTriggerDelayNs, SC_NS);
      }
    }

    if(mEventGen->getTriggeredEventCount() == mNumEvents) {
      // When we have reached the desired number of events, allow simulation to run for
      // another X us to allow readout of data remaining in MEBs, FIFOs etc.
      next_trigger(100, SC_US);
      simulation_done = true;
      mEventGen->stopEventGeneration();
    } else {
      next_trigger(mEventGen->E_triggered_event);
    }
  }
}


///@brief SystemC method for feeding QED and noise events that are
///       not associated with a trigger to the ALPIDE chips.
void StimuliITS::stimuliQedNoiseEventMethod(void)
{
    // Get hits for this event, and "feed" them to the ITS detector
    auto event_hits = mEventGen->getUntriggeredEvent();

    if(mSingleChipSimulation) {
      for(auto it = event_hits.begin(); it != event_hits.end(); it++)
        mAlpide->pixelInput(*it);
    }
    else {
      for(auto it = event_hits.begin(); it != event_hits.end(); it++)
        mITS->pixelInput(*it);
    }
}


///@brief SystemC method for generating triggers in system continuous mode
///       This is the continuous mode at the _system level_, which means that
///       periodic triggers are genrated and sent to the chips.
///       Note that the continuous/triggered mode at the _chip level_ is decoupled
///       from this in the simulation. At the chip level the difference between
///       the triggered and continuous mode parameters is in how the chip handles
///       the multi event buffers and incoming triggers. How the strobe is set up
///       and whether the triggers are periodic or not is irrelevant to the mode
///       in the chip.
void StimuliITS::continuousTriggerMethod(void)
{
  if(mSingleChipSimulation)
    mReadoutUnit->E_trigger_in.notify(mTriggerDelayNs, SC_NS);
  else
    mITS->E_trigger_in.notify(mTriggerDelayNs, SC_NS);

  next_trigger(mSystemContinuousPeriodNs, SC_NS);
}


///@brief This SystemC method just toggles the s_physics_event for a clock cycle
///       signal every time we get an E_triggered_event from the event generator,
///       so that we can have a signal for this that we can add to the trace file.
void StimuliITS::physicsEventSignalMethod(void)
{
  if(s_physics_event.read() == true) {
    s_physics_event.write(false);
    next_trigger(mEventGen->E_triggered_event);
  } else {
    s_physics_event.write(true);
    next_trigger(25,SC_NS);
  }
}


///@brief Add SystemC signals to log in VCD trace file.
///@param[in,out] wf VCD waveform file pointer
void StimuliITS::addTraces(sc_trace_file *wf) const
{
  sc_trace(wf, s_physics_event, "PHYSICS_EVENT");
  sc_trace(wf, s_its_busy, "its_busy");

  if(mSingleChipSimulation) {
    sc_trace(wf, s_alpide_data_line, "alpide_data_line");
    mAlpide->addTraces(wf, "");
  } else {
    mITS->addTraces(wf, "");
  }
}


void StimuliITS::writeStimuliInfo(void) const
{
  std::string info_filename = mOutputPath + std::string("/simulation_info.txt");
  ofstream info_file(info_filename);

  if(!info_file.is_open()) {
    std::cerr << "Error opening simulation info file: " << info_filename << std::endl;
    return;
  }

  info_file << "Number of triggered events requested: " << mNumEvents << std::endl;
  info_file << "Number of triggered events simulated: ";
  info_file << mEventGen->getTriggeredEventCount() << std::endl;

  info_file << "Number of untriggered events requested: " << 0 << std::endl;
  info_file << "Number of untriggered events simulated: ";
  info_file << mEventGen->getUntriggeredEventCount() << std::endl;
}
