/**
 * @file   StimuliBase.cpp
 * @author Simon Voigt Nesbo
 * @date   November 19, 2018
 * @brief  Source file for stimuli base class for Alpide Dataflow SystemC model
 */

#include "StimuliBase.hpp"

///@brief Constructor for stimuli base class.
///@param[in] settings QSettings object with simulation settings.
///@param[in] output_path Path to store output files generated by the StimuliBase class
StimuliBase::StimuliBase(sc_core::sc_module_name name,
                         QSettings* settings,
                         std::string output_path)
  : sc_core::sc_module(name)
{
  mOutputPath = output_path;

  // Initialize variables for StimuliBase object
  mNumEvents = settings->value("simulation/n_events").toULongLong();
  mSingleChipSimulation = settings->value("simulation/single_chip").toBool();
  mContinuousMode = settings->value("simulation/continuous_mode").toBool();
  mStrobeActiveNs = settings->value("event/strobe_active_length_ns").toUInt();
  mStrobeInactiveNs = settings->value("event/strobe_inactive_length_ns").toUInt();
  mTriggerDelayNs = settings->value("event/trigger_delay_ns").toUInt();
}
